package com.example.localmessagetranscation.mapper.jimisun;

import com.example.localmessagetranscation.entity.UserMessage;
import com.example.localmessagetranscation.entity.UserMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface UserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    long countByExample(UserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int deleteByExample(UserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int insert(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int insertSelective(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    List<UserMessage> selectByExampleWithRowbounds(UserMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    List<UserMessage> selectByExample(UserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    UserMessage selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMessage record, @Param("example") UserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMessage record, @Param("example") UserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMessage record);
}